INFO - (10/19/2024 12:36:14 PM): [PID: 2998] Starting the script (Line: 18 [main.py])
INFO - (10/19/2024 04:31:13 PM): [PID: 3041] Starting the script (Line: 18 [main.py])
INFO - (10/19/2024 08:15:06 PM): [PID: 2856] Starting the script (Line: 18 [main.py])
INFO - (10/19/2024 10:51:24 PM): [PID: 25997] Starting the script (Line: 18 [main.py])
INFO - (10/19/2024 11:09:19 PM): [PID: 27371] Starting the script (Line: 20 [main.py])
INFO - (10/19/2024 11:10:36 PM): [PID: 27428] Starting the script (Line: 20 [main.py])
INFO - (10/19/2024 11:13:40 PM): [PID: 27523] Starting the script (Line: 20 [main.py])
INFO - (10/19/2024 11:16:53 PM): [PID: 27637] Starting the script (Line: 20 [main.py])
INFO - (10/19/2024 11:16:56 PM): [PID: 27637] Adding event to Google Calendar (Line: 11 [add_event_to_google_calendar.py])
INFO - (10/19/2024 11:16:57 PM): [PID: 27637] file_cache is only supported with oauth2client<4.0.0 (Line: 49 [__init__.py])
INFO - (10/19/2024 11:16:59 PM): [PID: 27637] Event created: https://www.google.com/calendar/event?eid=MDk0cXBjdGIwcTdsMmxkbHY3M25saTdodm8gc2F6aWIuaHVuay4xMjNAbQ (Line: 91 [my_google_calendar.py])
INFO - (10/19/2024 11:16:59 PM): [PID: 27637] Event added to Google Calendar (Line: 14 [add_event_to_google_calendar.py])
INFO - (10/19/2024 11:16:59 PM): [PID: 27637] Adding event to Google Calendar (Line: 11 [add_event_to_google_calendar.py])
INFO - (10/19/2024 11:17:00 PM): [PID: 27637] Event created: https://www.google.com/calendar/event?eid=cGs1b204bzczNzNnazUxbmI5Ym9lazljOWMgc2F6aWIuaHVuay4xMjNAbQ (Line: 91 [my_google_calendar.py])
INFO - (10/19/2024 11:17:00 PM): [PID: 27637] Event added to Google Calendar (Line: 14 [add_event_to_google_calendar.py])
INFO - (10/19/2024 11:17:00 PM): [PID: 27637] Adding event to Google Calendar (Line: 11 [add_event_to_google_calendar.py])
INFO - (10/19/2024 11:17:02 PM): [PID: 27637] Event created: https://www.google.com/calendar/event?eid=aG1kNzlrNW9jYmRidjBmbWlhMmFuN3FsOTggc2F6aWIuaHVuay4xMjNAbQ (Line: 91 [my_google_calendar.py])
INFO - (10/19/2024 11:17:02 PM): [PID: 27637] Event added to Google Calendar (Line: 14 [add_event_to_google_calendar.py])
INFO - (10/19/2024 11:17:21 PM): [PID: 27649] Starting the script (Line: 20 [main.py])
INFO - (10/19/2024 11:17:24 PM): [PID: 27649] Adding event to Google Calendar (Line: 11 [add_event_to_google_calendar.py])
INFO - (10/19/2024 11:17:25 PM): [PID: 27649] file_cache is only supported with oauth2client<4.0.0 (Line: 49 [__init__.py])
INFO - (10/19/2024 11:17:25 PM): [PID: 27649] Event with the same summary already exists on 1900-01-02. (Line: 69 [my_google_calendar.py])
INFO - (10/19/2024 11:17:25 PM): [PID: 27649] Event added to Google Calendar (Line: 14 [add_event_to_google_calendar.py])
INFO - (10/19/2024 11:17:25 PM): [PID: 27649] Adding event to Google Calendar (Line: 11 [add_event_to_google_calendar.py])
INFO - (10/19/2024 11:17:26 PM): [PID: 27649] Event with the same summary already exists on 1900-01-01. (Line: 69 [my_google_calendar.py])
INFO - (10/19/2024 11:17:26 PM): [PID: 27649] Event added to Google Calendar (Line: 14 [add_event_to_google_calendar.py])
INFO - (10/19/2024 11:17:26 PM): [PID: 27649] Adding event to Google Calendar (Line: 11 [add_event_to_google_calendar.py])
INFO - (10/19/2024 11:17:27 PM): [PID: 27649] Event with the same summary already exists on 1900-01-01. (Line: 69 [my_google_calendar.py])
INFO - (10/19/2024 11:17:27 PM): [PID: 27649] Event added to Google Calendar (Line: 14 [add_event_to_google_calendar.py])
INFO - (10/19/2024 11:18:55 PM): [PID: 27861] Starting the script (Line: 20 [main.py])
INFO - (10/19/2024 11:18:59 PM): [PID: 27861] file_cache is only supported with oauth2client<4.0.0 (Line: 49 [__init__.py])
INFO - (10/19/2024 11:18:59 PM): [PID: 27861] Event with the same summary already exists on 1900-01-02. (Line: 69 [my_google_calendar.py])
INFO - (10/19/2024 11:19:00 PM): [PID: 27861] Event with the same summary already exists on 1900-01-01. (Line: 69 [my_google_calendar.py])
INFO - (10/19/2024 11:19:01 PM): [PID: 27861] Event with the same summary already exists on 1900-01-01. (Line: 69 [my_google_calendar.py])
INFO - (10/19/2024 11:19:52 PM): [PID: 28012] Starting the script (Line: 20 [main.py])
INFO - (10/19/2024 11:19:55 PM): [PID: 28012] file_cache is only supported with oauth2client<4.0.0 (Line: 49 [__init__.py])
INFO - (10/19/2024 11:19:57 PM): [PID: 28012] Event created: https://www.google.com/calendar/event?eid=YzZwanU3bjgxMDBxbWFzajNoYnVqdHZyaDAgc2F6aWIuaHVuay4xMjNAbQ (Line: 91 [my_google_calendar.py])
INFO - (10/19/2024 11:19:59 PM): [PID: 28012] Event created: https://www.google.com/calendar/event?eid=bGZiOHBrZzZqN2VnaXFqZHZlZnJzdnVoaWMgc2F6aWIuaHVuay4xMjNAbQ (Line: 91 [my_google_calendar.py])
INFO - (10/19/2024 11:20:00 PM): [PID: 28012] Event created: https://www.google.com/calendar/event?eid=YzB2aG11aGZpdmVtZm1lMm52bzV1MnBwcW8gc2F6aWIuaHVuay4xMjNAbQ (Line: 91 [my_google_calendar.py])
INFO - (10/19/2024 11:22:07 PM): [PID: 28222] Starting the script (Line: 20 [main.py])
INFO - (10/19/2024 11:22:10 PM): [PID: 28222] file_cache is only supported with oauth2client<4.0.0 (Line: 49 [__init__.py])
INFO - (10/19/2024 11:22:10 PM): [PID: 28222] Creating event: Saturday Night Live on 2024-10-20 00:29:00+05:30 to 2024-10-20 01:29:00+05:30. (Line: 68 [my_google_calendar.py])
INFO - (10/19/2024 11:22:11 PM): [PID: 28222] Event with the same summary already exists on 2024-10-20. (Line: 71 [my_google_calendar.py])
INFO - (10/19/2024 11:22:11 PM): [PID: 28222] Creating event: Bleach on 2024-10-19 20:30:00+05:30 to 2024-10-19 21:30:00+05:30. (Line: 68 [my_google_calendar.py])
INFO - (10/19/2024 11:22:11 PM): [PID: 28222] Event with the same summary already exists on 2024-10-19. (Line: 71 [my_google_calendar.py])
INFO - (10/19/2024 11:22:11 PM): [PID: 28222] Creating event: Blue Lock on 2024-10-19 11:30:00+05:30 to 2024-10-19 12:30:00+05:30. (Line: 68 [my_google_calendar.py])
INFO - (10/19/2024 11:22:12 PM): [PID: 28222] Event with the same summary already exists on 2024-10-19. (Line: 71 [my_google_calendar.py])
INFO - (10/19/2024 11:28:15 PM): [PID: 30168] Starting the script (Line: 20 [main.py])
INFO - (10/19/2024 11:28:18 PM): [PID: 30168] file_cache is only supported with oauth2client<4.0.0 (Line: 49 [__init__.py])
INFO - (10/19/2024 11:28:18 PM): [PID: 30168] Creating event: Sword Art Online Alternative Gun Gale Online on 2024-10-19 11:00:00+05:30 to 2024-10-19 12:00:00+05:30. (Line: 68 [my_google_calendar.py])
INFO - (10/19/2024 11:28:20 PM): [PID: 30168] Event created: https://www.google.com/calendar/event?eid=MXFpMzZkNGhhbXZjZmtkcGN0cjZqbG1lazAgc2F6aWIuaHVuay4xMjNAbQ (Line: 94 [my_google_calendar.py])
INFO - (10/19/2024 11:28:20 PM): [PID: 30168] Creating event: Ao no Exorcist on 2024-10-19 22:30:00+05:30 to 2024-10-19 23:30:00+05:30. (Line: 68 [my_google_calendar.py])
INFO - (10/19/2024 11:28:22 PM): [PID: 30168] Event created: https://www.google.com/calendar/event?eid=MGNxcTlrOTUwcWFzaTJ1dmprbnRndjZiYWcgc2F6aWIuaHVuay4xMjNAbQ (Line: 94 [my_google_calendar.py])
INFO - (10/19/2024 11:33:00 PM): [PID: 31249] Starting the script (Line: 20 [main.py])
INFO - (10/19/2024 11:33:03 PM): [PID: 31249] file_cache is only supported with oauth2client<4.0.0 (Line: 49 [__init__.py])
INFO - (10/19/2024 11:33:03 PM): [PID: 31249] Creating event: summary='Saturday Night Live' on start_time=datetime.datetime(2024, 10, 20, 0, 29, tzinfo=<DstTzInfo 'Asia/Kolkata' IST+5:30:00 STD>) to end_time=datetime.datetime(2024, 10, 20, 1, 29, tzinfo=<DstTzInfo 'Asia/Kolkata' IST+5:30:00 STD>). (Line: 68 [my_google_calendar.py])
INFO - (10/19/2024 11:33:05 PM): [PID: 31249] Event created: https://www.google.com/calendar/event?eid=ZnNqZGZlb2hzbmdtNHNpbmF1dHUyZ2E0aGMgc2F6aWIuaHVuay4xMjNAbQ (Line: 94 [my_google_calendar.py])
INFO - (10/19/2024 11:33:05 PM): [PID: 31249] Creating event: summary='Bleach' on start_time=datetime.datetime(2024, 10, 19, 20, 30, tzinfo=<DstTzInfo 'Asia/Kolkata' IST+5:30:00 STD>) to end_time=datetime.datetime(2024, 10, 19, 21, 30, tzinfo=<DstTzInfo 'Asia/Kolkata' IST+5:30:00 STD>). (Line: 68 [my_google_calendar.py])
INFO - (10/19/2024 11:33:07 PM): [PID: 31249] Event created: https://www.google.com/calendar/event?eid=cGZ0bzU0NW5mdWRyMzNyZmR1a21qNzdtMzggc2F6aWIuaHVuay4xMjNAbQ (Line: 94 [my_google_calendar.py])
INFO - (10/19/2024 11:33:07 PM): [PID: 31249] Creating event: summary='Blue Lock' on start_time=datetime.datetime(2024, 10, 19, 11, 30, tzinfo=<DstTzInfo 'Asia/Kolkata' IST+5:30:00 STD>) to end_time=datetime.datetime(2024, 10, 19, 12, 30, tzinfo=<DstTzInfo 'Asia/Kolkata' IST+5:30:00 STD>). (Line: 68 [my_google_calendar.py])
INFO - (10/19/2024 11:33:08 PM): [PID: 31249] Event created: https://www.google.com/calendar/event?eid=M2ljNjZtMGZxbm43YWNpMDZlbWpwczY0cTQgc2F6aWIuaHVuay4xMjNAbQ (Line: 94 [my_google_calendar.py])
INFO - (10/19/2024 11:33:42 PM): [PID: 31279] Starting the script (Line: 20 [main.py])
INFO - (10/19/2024 11:33:45 PM): [PID: 31279] file_cache is only supported with oauth2client<4.0.0 (Line: 49 [__init__.py])
INFO - (10/19/2024 11:33:45 PM): [PID: 31279] Creating event: summary='Sword Art Online Alternative Gun Gale Online' on start_time=datetime.datetime(2024, 10, 19, 11, 0, tzinfo=<DstTzInfo 'Asia/Kolkata' IST+5:30:00 STD>) to end_time=datetime.datetime(2024, 10, 19, 12, 0, tzinfo=<DstTzInfo 'Asia/Kolkata' IST+5:30:00 STD>). (Line: 68 [my_google_calendar.py])
INFO - (10/19/2024 11:33:46 PM): [PID: 31279] Event with the same summary='Sword Art Online Alternative Gun Gale Online' already exists on 2024-10-19. (Line: 71 [my_google_calendar.py])
INFO - (10/19/2024 11:33:46 PM): [PID: 31279] Creating event: summary='Ao no Exorcist' on start_time=datetime.datetime(2024, 10, 19, 22, 30, tzinfo=<DstTzInfo 'Asia/Kolkata' IST+5:30:00 STD>) to end_time=datetime.datetime(2024, 10, 19, 23, 30, tzinfo=<DstTzInfo 'Asia/Kolkata' IST+5:30:00 STD>). (Line: 68 [my_google_calendar.py])
INFO - (10/19/2024 11:33:47 PM): [PID: 31279] Event with the same summary='Ao no Exorcist' already exists on 2024-10-19. (Line: 71 [my_google_calendar.py])
INFO - (10/19/2024 11:43:43 PM): [PID: 32683] Starting the script (Line: 20 [main.py])
INFO - (10/19/2024 11:43:46 PM): [PID: 32683] file_cache is only supported with oauth2client<4.0.0 (Line: 49 [__init__.py])
INFO - (10/19/2024 11:43:46 PM): [PID: 32683] Creating event: summary='Sword Art Online Alternative Gun Gale Online' on start_time=datetime.datetime(2024, 10, 19, 11, 0, tzinfo=<DstTzInfo 'Asia/Kolkata' IST+5:30:00 STD>) to end_time=datetime.datetime(2024, 10, 19, 12, 0, tzinfo=<DstTzInfo 'Asia/Kolkata' IST+5:30:00 STD>). (Line: 68 [my_google_calendar.py])
INFO - (10/19/2024 11:43:48 PM): [PID: 32683] Event created: https://www.google.com/calendar/event?eid=bWdkcW85YjR1aGxnOXZicmE2aGMwM3BkcWMgc2F6aWIuaHVuay4xMjNAbQ (Line: 94 [my_google_calendar.py])
INFO - (10/19/2024 11:43:48 PM): [PID: 32683] Creating event: summary='Ao no Exorcist' on start_time=datetime.datetime(2024, 10, 19, 22, 30, tzinfo=<DstTzInfo 'Asia/Kolkata' IST+5:30:00 STD>) to end_time=datetime.datetime(2024, 10, 19, 23, 30, tzinfo=<DstTzInfo 'Asia/Kolkata' IST+5:30:00 STD>). (Line: 68 [my_google_calendar.py])
INFO - (10/19/2024 11:43:49 PM): [PID: 32683] Event created: https://www.google.com/calendar/event?eid=bHJ1NWVnZWNvdDIzZnBhaGtvb2JqMXZyNzggc2F6aWIuaHVuay4xMjNAbQ (Line: 94 [my_google_calendar.py])
ERROR - (10/19/2024 11:43:49 PM): [PID: 32683] Uncaught exception (Line: 77 [logconfig.py])
Traceback (most recent call last):
  File "/home/shazib/Desktop/Folder/python/Notify_about_series/main.py", line 33, in <module>
    add_event(series_data)
        # _add_event_to_google_calendar(series[0], series[2], series[1])
  File "/home/shazib/Desktop/Folder/python/Notify_about_series/utility/add_event_to_google_calendar.py", line 32, in add_event
    os.system()
TypeError: system() missing required argument 'command' (pos 1)
INFO - (10/19/2024 11:45:36 PM): [PID: 32861] Starting the script (Line: 20 [main.py])
INFO - (10/19/2024 11:45:39 PM): [PID: 32861] file_cache is only supported with oauth2client<4.0.0 (Line: 49 [__init__.py])
INFO - (10/19/2024 11:45:39 PM): [PID: 32861] Creating event: summary='Sword Art Online Alternative Gun Gale Online' on start_time=datetime.datetime(2024, 10, 19, 11, 0, tzinfo=<DstTzInfo 'Asia/Kolkata' IST+5:30:00 STD>) to end_time=datetime.datetime(2024, 10, 19, 12, 0, tzinfo=<DstTzInfo 'Asia/Kolkata' IST+5:30:00 STD>). (Line: 68 [my_google_calendar.py])
INFO - (10/19/2024 11:45:41 PM): [PID: 32861] Event created: https://www.google.com/calendar/event?eid=ZnVmbTFtZ3IzaWUzNXN1cDZpaWgwNWJkYWMgc2F6aWIuaHVuay4xMjNAbQ (Line: 94 [my_google_calendar.py])
INFO - (10/19/2024 11:45:41 PM): [PID: 32861] Creating event: summary='Ao no Exorcist' on start_time=datetime.datetime(2024, 10, 19, 22, 30, tzinfo=<DstTzInfo 'Asia/Kolkata' IST+5:30:00 STD>) to end_time=datetime.datetime(2024, 10, 19, 23, 30, tzinfo=<DstTzInfo 'Asia/Kolkata' IST+5:30:00 STD>). (Line: 68 [my_google_calendar.py])
INFO - (10/19/2024 11:45:43 PM): [PID: 32861] Event created: https://www.google.com/calendar/event?eid=bHN1MWhqdnQ0cmQwdXYxYWk2OWp0M2ZiZWcgc2F6aWIuaHVuay4xMjNAbQ (Line: 94 [my_google_calendar.py])
INFO - (10/19/2024 11:49:33 PM): [PID: 33183] Starting the script (Line: 20 [main.py])
INFO - (10/19/2024 11:56:04 PM): [PID: 33474] Starting the script (Line: 21 [main.py])
INFO - (10/19/2024 11:56:07 PM): [PID: 33474] file_cache is only supported with oauth2client<4.0.0 (Line: 49 [__init__.py])
INFO - (10/19/2024 11:56:07 PM): [PID: 33474] Creating event: summary='Saturday Night Live' on start_time=datetime.datetime(2024, 10, 20, 0, 29, tzinfo=<DstTzInfo 'Asia/Kolkata' IST+5:30:00 STD>) to end_time=datetime.datetime(2024, 10, 20, 1, 29, tzinfo=<DstTzInfo 'Asia/Kolkata' IST+5:30:00 STD>). (Line: 68 [my_google_calendar.py])
INFO - (10/19/2024 11:56:09 PM): [PID: 33474] Event created: https://www.google.com/calendar/event?eid=c2poNDBhY20wYzFmajJuOXM2Z3JkdmtnOTQgc2F6aWIuaHVuay4xMjNAbQ (Line: 94 [my_google_calendar.py])
INFO - (10/19/2024 11:56:09 PM): [PID: 33474] Creating event: summary='Bleach' on start_time=datetime.datetime(2024, 10, 19, 20, 30, tzinfo=<DstTzInfo 'Asia/Kolkata' IST+5:30:00 STD>) to end_time=datetime.datetime(2024, 10, 19, 21, 30, tzinfo=<DstTzInfo 'Asia/Kolkata' IST+5:30:00 STD>). (Line: 68 [my_google_calendar.py])
INFO - (10/19/2024 11:56:11 PM): [PID: 33474] Event created: https://www.google.com/calendar/event?eid=amI1NzBiM2VqNDI5cmFvdW9vYWNlb2tydGcgc2F6aWIuaHVuay4xMjNAbQ (Line: 94 [my_google_calendar.py])
INFO - (10/19/2024 11:56:11 PM): [PID: 33474] Creating event: summary='Blue Lock' on start_time=datetime.datetime(2024, 10, 19, 11, 30, tzinfo=<DstTzInfo 'Asia/Kolkata' IST+5:30:00 STD>) to end_time=datetime.datetime(2024, 10, 19, 12, 30, tzinfo=<DstTzInfo 'Asia/Kolkata' IST+5:30:00 STD>). (Line: 68 [my_google_calendar.py])
INFO - (10/19/2024 11:56:12 PM): [PID: 33474] Event created: https://www.google.com/calendar/event?eid=M3NvMDhzcjJlY2ZiOGEzbGNzbDEydTY4ODQgc2F6aWIuaHVuay4xMjNAbQ (Line: 94 [my_google_calendar.py])
ERROR - (10/19/2024 11:56:12 PM): [PID: 33474] Uncaught exception (Line: 77 [logconfig.py])
Traceback (most recent call last):
  File "/home/shazib/Desktop/Folder/python/Notify_about_series/main.py", line 36, in <module>
    print(get_series_data_for_today_and_next_no_of_days(page_content, 20))
  File "/home/shazib/Desktop/Folder/python/Notify_about_series/utility/get_series_data_for_current_day.py", line 30, in get_series_data_for_today_and_next_no_of_days
    day_data = day_data.parent.parent
AttributeError: 'NoneType' object has no attribute 'parent'
INFO - (10/19/2024 11:56:33 PM): [PID: 33494] Starting the script (Line: 21 [main.py])
INFO - (10/19/2024 11:56:37 PM): [PID: 33494] file_cache is only supported with oauth2client<4.0.0 (Line: 49 [__init__.py])
INFO - (10/19/2024 11:56:37 PM): [PID: 33494] Creating event: summary='Sword Art Online Alternative Gun Gale Online' on start_time=datetime.datetime(2024, 10, 19, 11, 0, tzinfo=<DstTzInfo 'Asia/Kolkata' IST+5:30:00 STD>) to end_time=datetime.datetime(2024, 10, 19, 12, 0, tzinfo=<DstTzInfo 'Asia/Kolkata' IST+5:30:00 STD>). (Line: 68 [my_google_calendar.py])
INFO - (10/19/2024 11:56:38 PM): [PID: 33494] Event with the same summary='Sword Art Online Alternative Gun Gale Online' already exists on 2024-10-19. (Line: 71 [my_google_calendar.py])
INFO - (10/19/2024 11:56:38 PM): [PID: 33494] Creating event: summary='Ao no Exorcist' on start_time=datetime.datetime(2024, 10, 19, 22, 30, tzinfo=<DstTzInfo 'Asia/Kolkata' IST+5:30:00 STD>) to end_time=datetime.datetime(2024, 10, 19, 23, 30, tzinfo=<DstTzInfo 'Asia/Kolkata' IST+5:30:00 STD>). (Line: 68 [my_google_calendar.py])
INFO - (10/19/2024 11:56:38 PM): [PID: 33494] Event with the same summary='Ao no Exorcist' already exists on 2024-10-19. (Line: 71 [my_google_calendar.py])
ERROR - (10/19/2024 11:56:38 PM): [PID: 33494] Uncaught exception (Line: 77 [logconfig.py])
Traceback (most recent call last):
  File "/home/shazib/Desktop/Folder/python/Notify_about_series/main.py", line 36, in <module>
    print(get_series_data_for_today_and_next_no_of_days(page_content, 20))
  File "/home/shazib/Desktop/Folder/python/Notify_about_series/utility/get_series_data_for_current_day.py", line 30, in get_series_data_for_today_and_next_no_of_days
    day_data = day_data.parent.parent
AttributeError: 'NoneType' object has no attribute 'parent'
